on: [push]
name: databrideployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ResourceGroupName: sqldb-rg
      ResourceGroupLocation: "eastus"
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    

  
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.ResourceGroupName }}
        template: azuredeploy.json
        parameters: azuredeploy.parameters.json
        
##    - uses: azure/arm-deploy@v1
#      with:
#        resourceGroupName: ${{ env.ResourceGroupName }}
#        template: apache2-on-ubuntu-vm/azuredeploy.json
#        parameters: apache2-on-ubuntu-vm/azuredeploy.parameters.json  

 
